### ISSUE TITLE
Some minor issues with some text in the EADME.md

### ISSUE THREAD

**Issue by nguyenhongphu** [SINTEF-9012/kafka-mqtt-sink-connector#2]
There are some copy and paste issues. 
Maybe you forgot to change the corresponding text for the sink connector :)

For example: 
"Connect in general Build this java maven project, but navigating to root kafka-mqtt-source-connector in a terminal and typing:"
"root kafka-mqtt-source-connector" should be **kafka-mqtt-sink-connector**

"Copy the kafka-mqtt-source-connector-"version".jar" should be "Copy the kafka-mqtt-**sink**-connector-"version".jar" ?

Steps 5 and 6 should start from new lines. 

In Step 7. Start our connector by posting the following command to the Connect REST-interface:
curl -s -X POST -H 'Content-Type: application/json' http://127.0.0.1:19005/connectors -d '{"name":"mqtt-sink-connector","config":{"connector.class":"com.sintef.asam.MqttSinkConnector","tasks.max":"1","mqtt.connector.broker.uri":"tcp://localhost:1883", "mqtt.connector.broker.topics.regex":"test*","mqtt.connector.mqtt_topic_key":"topic"}}'

I got an error if using "mqtt.connector.broker.topics.regex". Should it be without "mqtt.connector.broker." ?

curl -s -X POST -H 'Content-Type: application/json' http://127.0.0.1:19005/connectors -d '{"name":"mqtt-sink-connector3","config":{"connector.class":"com.sintef.asam.MqttSinkConnector","tasks.max":"1","mqtt.connector.broker.uri":"tcp://localhost:1883", "topics":"test","mqtt.connector.mqtt_topic_key":"topic"}}'

**Comment by brice-morin** [comment]
Hi Phu, I confirm those issues. You've now been invited to SINTEF-9012 so that it will be more efficient to fix small issues than to report them :-)

**Comment by nguyenhongphu** [comment]
Many thanks :-)
